### ISSUE TITLE
Maintainers wanted!

### ISSUE THREAD

**Issue by armanbilge** [http4s/http4s-jetty-client#3]
Please comment if you are interested in helping to maintain this module :) Thanks!

**Comment by rossabaker** [comment]
I was thinking this one would live into http4s-jetty.  Assuming client and server are on the same release cycle, and they remain part of the same Jetty distribution, it makes sense to me.

**Comment by armanbilge** [comment]
Yes, this just dawned on me as well, sorry. I guess the trick I should have used is git merge with unrelated histories?

**Comment by rossabaker** [comment]
Yeah, that would have worked, and could work now.  The filtering and the rewriting issue links in the log is the tricky part.  I can give it a shot.

**Comment by armanbilge** [comment]
If you can get a branch up with those things done, I'm happy to fix up the build and CI stuff. Sorry for my mistake here!

**Comment by rossabaker** [comment]
No worries, it's easy, and I have Emacs.
